# Generated by Django 5.2.6 on 2025-09-14 05:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('expenses', '0002_alter_category_user_alter_expense_category_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='budget',
            name='month',
            field=models.PositiveIntegerField(blank=True, help_text='1-12 for monthly budget, leave blank for yearly', null=True),
        ),
        migrations.AddField(
            model_name='budget',
            name='year',
            field=models.PositiveIntegerField(default=2025, help_text='Year for this budget (required)'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='budget',
            name='limit',
            field=models.DecimalField(decimal_places=2, help_text='Budget limit for this category', max_digits=10),
        ),
    ]
