# Generated by Django 5.2.6 on 2025-09-14 05:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('expenses', '0003_budget_month_budget_year_alter_budget_limit'),
    ]

    operations = [
        migrations.AlterField(
            model_name='budget',
            name='year',
            field=models.PositiveIntegerField(default=2025, help_text='Year for this budget (required)'),
        ),
    ]
