# Generated by Django 5.2.6 on 2025-09-14 06:30

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('expenses', '0005_loan_loanpayment'),
    ]

    operations = [
        migrations.AddField(
            model_name='loan',
            name='duration_months',
            field=models.PositiveIntegerField(default=1, help_text='Duration in months'),
        ),
        migrations.AddField(
            model_name='loan',
            name='interest_rate',
            field=models.DecimalField(decimal_places=2, default=0.0, help_text='Interest rate %', max_digits=5),
        ),
        migrations.AddField(
            model_name='loanpayment',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='loan',
            name='name',
            field=models.CharField(help_text="Person's name", max_length=100),
        ),
    ]
