# Generated by Django 5.2.6 on 2025-09-14 07:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('expenses', '0006_loan_duration_months_loan_interest_rate_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='loan',
            name='duration_months',
        ),
        migrations.AlterField(
            model_name='loan',
            name='interest_rate',
            field=models.DecimalField(decimal_places=2, default=0.0, help_text='Monthly interest rate %', max_digits=5),
        ),
        migrations.AlterField(
            model_name='loan',
            name='name',
            field=models.CharField(max_length=100),
        ),
    ]
